export const MOCK_COMPANIES = [
  {
    id: 101,
    company_name: 'Northstar Commerce Co',
    package_tier: 'Virtual Office',
    email_1: 'ops@northstarcommerce.co',
    address: '6F Arca South Hub, Taguig City',
    delivery_count: 42,
    status: 'active',
  },
  {
    id: 102,
    company_name: 'Bayside Fabrication Inc',
    package_tier: 'Use of Address',
    email_1: 'admin@baysidefab.ph',
    address: 'Unit 305, BGC Corporate Center, Taguig',
    delivery_count: 17,
    status: 'active',
  },
  {
    id: 103,
    company_name: 'Solara Health Systems',
    package_tier: 'Dedicated Office',
    email_1: 'mailroom@solarahealth.io',
    address: '10th Floor, Midtown Plaza, Makati',
    delivery_count: 58,
    status: 'inactive',
  },
  {
    id: 104,
    company_name: 'Delta Wave Logistics',
    package_tier: 'Coworking Membership',
    email_1: 'support@deltawave-logistics.com',
    address: 'Suite 211, Cloverleaf Business Park, Quezon City',
    delivery_count: 9,
    status: 'active',
  },
  {
    id: 105,
    company_name: 'Rainline Ventures PH',
    package_tier: 'Virtual Office',
    email_1: 'hello@rainlineventures.ph',
    address: '2F Spectrum Center, Cebu IT Park, Cebu City',
    delivery_count: 24,
    status: 'active',
  },
  {
    id: 106,
    company_name: 'Atlas Insight Analytics',
    package_tier: 'Use of Address',
    email_1: 'contact@atlasinsight.ai',
    address: '4F Gateway Tower, Iloilo Business District',
    delivery_count: 11,
    status: 'inactive',
  },
  {
    id: 107,
    company_name: 'Harborline Digital Studio',
    package_tier: 'Virtual Office',
    email_1: 'team@harborlinedigital.com',
    address: '8F Pacific Hub, Davao Global Township',
    delivery_count: 33,
    status: 'active',
  },
  {
    id: 108,
    company_name: 'Aster Peak Technologies',
    package_tier: 'Dedicated Office',
    email_1: 'info@asterpeak.tech',
    address: 'Level 12, Greenfield Corporate Plaza, Mandaluyong',
    delivery_count: 65,
    status: 'active',
  },
]
